name: R-CMD-check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R dependencies
        run: |
          Rscript -e "install.packages(c('remotes','rcmdcheck','covr','testthat'), repos='https://cloud.r-project.org')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"

      - name: Run R CMD check
        run: |
          Rscript -e "
            rcmdcheck::rcmdcheck(args = c('--no-manual','--as-cran'), error_on = 'warning', check_dir = 'check');
            if (dir.exists('check')) {
              files <- list.files('check', pattern = 'testthat\\.Rout.*', recursive = TRUE, full.names = TRUE);
              for (f in files) cat(readLines(f), sep='\n')
            }
          "

      - name: Run tests and generate coverage
        run: |
          Rscript -e "library(covr); cov <- package_coverage(); print(cov)"
          Rscript -e "covr::codecov(quiet=FALSE)"

