name: test-coverage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.CODECOV_TOKEN  }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install dependencies
        run: |
          Rscript -e "install.packages('remotes', repos='https://cloud.r-project.org')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
          Rscript -e "install.packages('covr', repos='https://cloud.r-project.org')"

      - name: Test coverage
        run: Rscript -e "covr::codecov(quiet=FALSE)"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
